[2025-02-08T20:56:24.492+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2025-02-07T00:00:00+00:00 [queued]>
[2025-02-08T20:56:24.498+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2025-02-07T00:00:00+00:00 [queued]>
[2025-02-08T20:56:24.498+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T20:56:24.499+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-02-08T20:56:24.499+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T20:56:24.508+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-02-07 00:00:00+00:00
[2025-02-08T20:56:24.512+0000] {standard_task_runner.py:55} INFO - Started process 6307 to run task
[2025-02-08T20:56:24.515+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2025-02-07T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp01szw14j']
[2025-02-08T20:56:24.516+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask is_api_available
[2025-02-08T20:56:24.554+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2025-02-07T00:00:00+00:00 [running]> on host 7276d72461ca
[2025-02-08T20:56:24.592+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2025-02-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-02-07T00:00:00+00:00
[2025-02-08T20:56:24.593+0000] {http.py:120} INFO - Poking: api/
[2025-02-08T20:56:24.599+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2025-02-08T20:56:24.603+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2025-02-08T20:56:24.795+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2025-02-08T20:56:24.811+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20250207T000000, start_date=20250208T205624, end_date=20250208T205624
[2025-02-08T20:56:24.861+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-02-08T20:56:24.896+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
