[2025-02-08T20:56:23.872+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2025-02-07T00:00:00+00:00 [queued]>
[2025-02-08T20:56:23.877+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2025-02-07T00:00:00+00:00 [queued]>
[2025-02-08T20:56:23.878+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T20:56:23.878+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-02-08T20:56:23.878+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T20:56:23.885+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2025-02-07 00:00:00+00:00
[2025-02-08T20:56:23.889+0000] {standard_task_runner.py:55} INFO - Started process 6304 to run task
[2025-02-08T20:56:23.892+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2025-02-07T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp46y5tfz4']
[2025-02-08T20:56:23.893+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask create_table
[2025-02-08T20:56:23.927+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table scheduled__2025-02-07T00:00:00+00:00 [running]> on host 7276d72461ca
[2025-02-08T20:56:23.987+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2025-02-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-02-07T00:00:00+00:00
[2025-02-08T20:56:23.997+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2025-02-08T20:56:24.000+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2025-02-08T20:56:24.001+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2025-02-08T20:56:24.007+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20250207T000000, start_date=20250208T205623, end_date=20250208T205624
[2025-02-08T20:56:24.031+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-02-08T20:56:24.049+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
